language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t FreddieTheCat/docker-endritest -f Dockerfile.dev .
script:
  - docker run -e CI=true reddieTheCat/docker-endritest npm run test
